# -*- coding: utf-8 -*-
"""coleta_de_exercicios_numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O5hfb422vgBBb09MoUu8aesTQ8Ut47TV

# Coletando exercicios de numpy do site [w3resource](https://www.w3resource.com/python-exercises/numpy/index.php)

## 0.0 imports
"""

from bs4 import BeautifulSoup
import requests
import re

"""## Coletando dados"""

html = requests.get("https://www.w3resource.com/python-exercises/numpy/index.php")
html.text

soup = BeautifulSoup(html.text, "html.parser")

def has_href_but_no_itemscope(tag):
    return tag.has_attr('href') and not tag.has_attr('itemscope') and re.compile('/python-exercises/numpy/').search(tag['href'])

lista_links = soup.find_all(has_href_but_no_itemscope)

for link in lista_links:
  if not re.search('https://www.w3resource.com/python-exercises/numpy/', link['href']):

    link['href'] = link['href'].replace('/python-exercises/numpy/', 'https://www.w3resource.com/python-exercises/numpy/')

print('LISTA DE EXECICIOS')
print()

for i, link in enumerate(lista_links):
  print(f'  {i}  {link.text}')

print()
opcao = int(input('Escolha uma lista de exercicios: '))

novo_link = lista_links[opcao]

"""## parte 2"""

novo_link

response =  requests.get(novo_link['href'])
response.text

soup2 = BeautifulSoup(response.text, 'html.parser')
soup2

lista_questoes = []
for questao in soup2.article.find_all('p')[1:]:
  lista_questoes.append({
      'n_questao': None,
      'questao': questao.text,
      'link_resposta': None
  })
lista_questoes[1]

print(lista_questoes[7]["questao"])